name: Android Release

# 1
on:
  # 2
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # 3
  workflow_dispatch:

# 4
jobs:    
  # 5
  build:
    # 6
    runs-on: ubuntu-latest
    # 7
    steps:
      # 8
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          set-safe-directory: '*'
      # 9
      - name: Setup Java to compile Android project
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12.x'
          cache: 'gradle'
      # 10
      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          # 11
          flutter-version: "3.7.9"
          channel: 'stable'
          cache: true
      # 12
      - name: Create the keystore
        env:
          KEYSTORE_BASE64: ${{secrets.KEYSTORE_BASE64}}
        run: |
          # import keystore from secrets
          echo $KEYSTORE_BASE64 | base64 -d > $RUNNER_TEMP/my_production.keystore

      - name: Get dependencies
        run: flutter pub get

      
      # Runs a set of commands using the runners shell
      - name: Build android apk 
        run: flutter build  apk --obfuscate --split-debug-info=./split-debug-info-development  --split-per-abi

      - name: Publish Android Artefacts
        uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
      
      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:  
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{secrets.CREDENTIAL_FILE_CONTENT}}
          groups: developers
          file: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk